version: "3"

services:
  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  cache:
    image: redis:7-alpine

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    depends_on:
      - cache