flightsProviders:
  - loader: coding-challenge
    url: https://coding-challenge.powerus.de/flight/source1
    ttl: 3600000
  - loader: coding-challenge
    url: https://coding-challenge.powerus.de/flight/source2
    ttl: 3600000